class Data:
    APPID_KEY = 'appid'
    APPID = 'place id here'
    CITY_KEY = 'q'
    UNITS_KEY = 'units'
    UNITS = 'metric'
    BASE_URL = 'https://api.openweathermap.org/data/2.5/weather'
    MAIN_KEY = 'main'
    TEMP_KEY = 'temp'
    ENCODING = 'utf-8'